name: React-Advanced test push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: echo "test push request"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm install
      - name: Build project
        run: npm run build
